module.exports = {

    '=': 'button[name="equalsButton"]',
    '.': `button[name="decimalButton"]`,
    '0': `button[name="0Button"]`,
    '+': `button[name="addButton"]`,
    '1': `button[name="1Button"]`,
    '2': `button[name="2Button"]`,
    '3': `button[name="3Button"]`,
    '4': `button[name="4Button"]`,
    '5': `button[name="5Button"]`,
    '6': `button[name="6Button"]`,
    '-': `button[name="subtractButton"]`,
    '7': `button[name="7Button"]`,
    '8': `button[name="8Button"]`,
    '9': `button[name="9Button"']`,
    'x': `button[name="multiplyButton"]`,
    '/': `button[name="divideButton"]`,
    '%': `button[name="divideButton"]`,
    '+/-': `button[name="negativeButton"]`,
    'AC': `button[name="negativeButton"]`,
} 
